[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["svd2py"]

[tool.hatch.build.targets.sdist]
exclude = ["tests/*"]

[tool.hatch.version]
source = "vcs"

[project]
name = "svd2py"
dynamic = ["version"]
description = "CMSIS SVD file parser that allows to convert SVD format to Python data structure"
authors = [{ name = "Gembcior", email = "gembcior@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Environment :: Console",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = []

[project.optional-dependencies]
cli = [
  "pyyaml>=6.0",
  "click>=8.1",
]

[project.urls]
Homepage = "https://github.com/gembcior/svd2py"

[project.scripts]
svd2yaml = "svd2py.app:svd2yaml"
svd2json = "svd2py.app:svd2json"

[dependency-groups]
testing = [
  "pytest",
  "pytest-sugar",
  "pytest-cov",
  "pytest-clarity",
]
dev = [
  "ruff",
  "pre-commit",
]

[tool.ruff]
line-length = 160
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake8-future-annotations
    "FA",
    # flake8-annotations
    "ANN",
    # flake8-blind-except
    "BLE",
    # flake8-use-pathlib
    "PL",
    # pep8-naming
    "N",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]
